plan-wf-config: &plan-wf-config
  atmos-terraform-plan.yaml:
    inputs:
      component: "{{ .atmos_component }}"
      stack: "{{ .atmos_stack }}"
      upload: "false" # Only upload plan status to Atmos Pro for drift detection.

apply-wf-config: &apply-wf-config
  atmos-terraform-apply.yaml:
    inputs:
      component: "{{ .atmos_component }}"
      stack: "{{ .atmos_stack }}"
      github_environment: "{{ .vars.tenant }}-{{ .vars.stage }}"

settings:
  pro:
    enabled: true
    drift_detection:
      enabled: false # disabled by default and enabled for the plat org under _defaults.yaml
      detect:
        workflows: 
          <<: *plan-wf-config
          upload: "true" # Override the default value for this specific trigger.
      remediate:
        workflows: *apply-wf-config
    pull_request:
      opened:
        workflows: *plan-wf-config
      synchronize:
        workflows: *plan-wf-config
      reopened:
        workflows: *plan-wf-config
      merged:
        workflows: *apply-wf-config
    release:
      released:
        workflows: *apply-wf-config
