settings:
  pro:
    enabled: true
    pull_request:
      - trigger: [feature-branch]
        workflows:
          atmos-terraform-plan.yaml: # run the atmos-terraform-plan.yaml workflow via dispatch
            inputs: # with the following inputs
              component: "{{ .atmos_component }}"
              stack: "{{ .atmos_stack }}"
      - trigger: [merged]
        workflows:
          atmos-terraform-apply.yaml:
            inputs:
              component: "{{ .atmos_component }}"
              stack: "{{ .atmos_stack }}"
