# 'github-oidc-role' component vendoring config

# 'component.yaml' in the component folder is processed by the 'atmos' commands
# 'atmos vendor pull -c github-oidc-role' or 'atmos vendor pull --component github-oidc-role'

apiVersion: atmos/v1
kind: ComponentVendorConfig
spec:
  source:
    uri: github.com/cloudposse/terraform-aws-components.git//modules/github-oidc-role?ref={{ .Version }}
    version: 1.462.0
    included_paths:
      - "**/**"
    excluded_paths: []
    mixins: []
