# 's3-bucket' component vendoring config

# 'component.yaml' in the component folder is processed by the 'atmos' commands
# 'atmos vendor pull -c s3-bucket' or 'atmos vendor pull --component s3-bucket'

apiVersion: atmos/v1
kind: ComponentVendorConfig
spec:
  source:
    uri: github.com/cloudposse/terraform-aws-components.git//modules/s3-bucket?ref={{ .Version }}
    version: 1.462.0
    included_paths:
      - "**/**"
    excluded_paths: []
    mixins: []
