# 'dynamodb' component vendoring config

# 'component.yaml' in the component folder is processed by the 'atmos' commands
# 'atmos vendor pull -c dynamodb' or 'atmos vendor pull --component dynamodb'

apiVersion: atmos/v1
kind: ComponentVendorConfig
spec:
  source:
    uri: github.com/cloudposse/terraform-aws-components.git//modules/dynamodb?ref={{ .Version }}
    version: 1.462.0
    included_paths:
      - "**/**"
    excluded_paths: []
    mixins: []
