name: 👽 Atmos Terraform Plan

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Atmos Component"
        type: string
        default: "s3-bucket/mock-parent" # TODO used for testing, remove me
      stack:
        description: "Atmos Stack"
        type: string
        default: "plat-use2-dev" # TODO used for testing, remove me
      sha:
        description: "Commit SHA"
        type: string
      atmos_pro_run_id:
        description: "Atmos Pro Run ID"
        type: string
        default: "12345" # TODO used for testing, remove me

concurrency:
  group: "${{ inputs.component }}-${{ inputs.stack }}"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Plan ${{ inputs.stack }} ${{ inputs.component }}
    run-name: plan ${{ inputs.component }}/${{ inputs.stack }}/${{ inputs.atmos_pro_run_id}}
    runs-on:
      - "ubuntu-latest"
    steps:
      - name: Plan Atmos Component
        uses: cloudposse/github-action-atmos-terraform-plan@v2
        with:
          component: ${{ inputs.component }}
          stack: ${{ inputs.stack }}
          # sha: ${{ inputs.sha }}
          sha: ${{ github.sha }} # TODO used for testing, remove me
          atmos-version: ${{ vars.ATMOS_VERSION }}
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
