name: 👽 Atmos Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  affected:
    name: Trigger Affected

    runs-on:
      - "ubuntu-latest"

    steps:
      - name: Gather Affected Stacks
        id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@v3
        with:
          atmos-version: ${{ vars.ATMOS_VERSION }}
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
          # TODO
          # We need to specify what to include in this release
          # All changes since the last release?
          # s.t. base is last release, head is this release

      - name: Trigger Atmos Pro
        if: ${{ steps.affected.outputs.has-affected-stacks == 'true' }}
        shell: bash
        run: |
          echo "trigger atmos pro - apply"
          echo "${{ steps.affected.outputs.affected }}" > affected.json
          cat affected.json
          curl -X POST -H "Content-Type: application/json" -d @affected.json https://ngrok.mattcalhoun.com/api/affected-stacks
