name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  auto:
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@main
    with:
      publish: false
    secrets: inherit
